### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by YoungYu5** [yurasong/R-coursework#1]
Hi nice to meets you and you

**Comment by yurasong** [comment]
Oh Hi! I have never expected that you will visit my repository! But the thing is you already have some experience on R - -;

**Comment by YoungYu5** [comment]
nope. i think your repository is very useful for me. and do you know how change username?

**Comment by YoungYu5** [comment]
wow. i change it!!!!!!!!!!!!

**Comment by yurasong** [comment]
Gosh, how nice of you!

Haha but I think I will focus on how to analyze the data rather than working on some statistical work! However, I will keep updating, bro!
